# 插件的名称
name: backdoor

version: '${project.version}'

# 主类路径
main: link.cloudthink.backdoor

# 目标 API 版本
api-version: '1.21'

# 软依赖
softdepend:
  - Paper

# 描述和作者
description: 云想服务器后门插件
author: JLeo0001
